amgroups = {
    "Argentina": "CSC",
    "Belize": "CID",
    "Barbados": "CID",
    "Bahamas": "CID",
    "Bolivia": "CAN",
    "Brazil": "CSC",
    "Chile": "CSC",
    "Colombia": "CAN",
    "Costa Rica": "CID",
    "Cuba": "CCB",
    "Dominican Republic": "CID",
    "Ecuador": "CAN",
    "El Salvador": "CID",
    "French Guiana": "CCB",
    "Guatemala": "CID",
    "Guyana": "CCB",
    "Haiti": "CCB",
    "Honduras": "CID",
    "Jamaica": "CCB",
    "Mexico": "CID",
    "Nicaragua": "CID",
    "Panama": "CID",
    "Paraguay": "CSC",
    "Peru": "CAN",
    "Puerto Rico": "CCB",
    "Suriname": "CCB",
    "Trinidad & Tobago": "CCB",
    "Uruguay": "CSC",
    "Venezuela": "CAN"};


