twoLetter = {"Argentina": "AR",
    "Belize": "BZ",
    "Bolivia": "BO", 
    "Bahamas": "BH",
    "Barbados": "BB",
    "Brazil": "BR",
    "Canada": "CA",
    "Chile": "CL",
    "Colombia": "CO",
    "Costa Rica": "CR",
    "Cuba": "CU",
    "Dominican Republic": "DO",
    "Ecuador": "EC",
    "El Salvador": "SV",
    "French Guiana": "GF",
    "Guatemala": "GT",
    "Guyana": "GY",
    "Haiti": "HT",
    "Honduras": "HN",
    "Jamaica": "JM",
    "Mexico": "MX",
    "Nicaragua": "NI",
    "Panama": "PA",
    "Paraguay": "PY",
    "Peru": "PE",
    "Puerto Rico": "PR",
    "Suriname": "SR",
    "Trinidad & Tobago": "TT",
    "Uruguay": "UY",
    "Venezuela": "VE",
    "USA": "US",
    "LAC": "LC",
    "China": "CN",
    "India": "IN",
    "World": "WD",
    "Europe": "EU" ,
    "Austria": "AU",
    "Belgium": "BE",
    "Croatia": "HR",
    "Denmark": "DK",
    "Finland": "FI",
    "France": "FR",
    "Israel": "IL",
    "Japan": "JP",
    "Germany": "DE",
    "Italy": "IT",
    "Korea": "KR",
    "Norway": "NO",
    "Spain": "ES",
    "Switzerland": "CH",
    "Netherlands": "NL",
    "Portugal": "PT",
    "Slovenia": "SI",
    "Sweden": "SE",
    "United Kingdom": "UK",
    "Central America": "CT",
    "North America": "NA",
    "Andean": "CAN",
    "Caribbean": "CRB",
    "Southern Cone": "CSC"
};

