threeLetter = {"Argentina": "ARG",
    "Belize": "BLZ",
    "Bolivia": "BOL",
    "Bahamas": "BHA",
    "Barbados": "BAR",
    "Brazil": "BRA",
    "Canada" : "CAN",
    "Chile": "CHL",
    "Colombia": "COL",
    "Costa Rica": "CRI",
    "Cuba": "CUB",
    "Dominican Republic": "DOM",
    "Ecuador": "ECU",
    "El Salvador": "SLV",
    "French Guiana": "GUF",
    "Guatemala": "GTM",
    "Guyana": "GUY",
    "Haiti": "HTI",
    "Honduras": "HND",
    "Jamaica": "JAM",
    "Mexico": "MEX",
    "Nicaragua": "NIC",
    "Panama": "PAN",
    "Paraguay": "PRY",
    "Peru": "PER",
    "Puerto Rico": "PRI",
    "Suriname": "SUR",
    "Trinidad & Tobago": "TTO",
    "Uruguay": "URY",
    "Venezuela": "VEN",
    "USA": "USA",
    "LAC": "LAC",
    "China": "CHN",
    "India": "IND",
    "World": "WLD",
    "Europe": "EUR",
    "Austria": "AUT",
    "Belgium": "BEL",
    "Croatia": "CRO",
    "Denmark": "DEN",
    "Finland": "FIN",
    "France": "FRA",
    "Israel": "ISR",
    "Japan": "JPN",
    "Germany": "GER",
    "Italy": "ITA",
    "Korea": "KOR",
    "Norway": "NOR",
    "Spain": "ESP",
    "Switzerland": "SWI",
    "Netherlands": "NED",
    "Portugal": "POR",
    "Slovenia": "SLO",
    "Sweden": "SWE",
    "United Kingdom": "UK",
    "Central America": "CEA",
    "North America": "NOA",
    "Andean": "CAN",
    "Caribbean": "CRB",
    "Southern Cone": "CSC"
};

